package chat;


/**
* chat/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 16 mars 2018 15 h 49 CET
*/

public interface ChatServerOperations 
{
  void register (chat.ChatClient client);
  void remove (chat.ChatClient client);
  void sendMessage (chat.Message message);
} // interface ChatServerOperations
