package chat;


/**
* chat/ChatClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 23 mars 2018 10 h 33 CET
*/

public abstract class ChatClientPOA extends org.omg.PortableServer.Servant
 implements chat.ChatClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getName", new java.lang.Integer (0));
    _methods.put ("updateClientList", new java.lang.Integer (1));
    _methods.put ("printMessage", new java.lang.Integer (2));
    _methods.put ("getColor", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
    _methods.put ("getImage", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/ChatClient/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // chat/ChatClient/updateClientList
       {
         chat.ChatClient clients[] = chat.ChatClientPackage.clientsHelper.read (in);
         this.updateClientList (clients);
         out = $rh.createReply();
         break;
       }

       case 2:  // chat/ChatClient/printMessage
       {
         chat.Message message = chat.MessageHelper.read (in);
         this.printMessage (message);
         out = $rh.createReply();
         break;
       }

       case 3:  // chat/ChatClient/getColor
       {
         chat.Color $result = null;
         $result = this.getColor ();
         out = $rh.createReply();
         chat.ColorHelper.write (out, $result);
         break;
       }

       case 4:  // chat/ChatClient/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 5:  // chat/ChatClient/getImage
       {
         org.omg.CORBA.Any $result = null;
         $result = this.getImage ();
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/ChatClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatClient _this() 
  {
    return ChatClientHelper.narrow(
    super._this_object());
  }

  public ChatClient _this(org.omg.CORBA.ORB orb) 
  {
    return ChatClientHelper.narrow(
    super._this_object(orb));
  }


} // class ChatClientPOA
