package chat;


/**
* chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 16 mars 2018 15 h 49 CET
*/

public interface ChatClientOperations 
{
  String getName ();
  void updateClientList (chat.ChatClient[] clients);
  void printMessage (chat.Message message);
} // interface ChatClientOperations
