package chat;

/**
* chat/ChatChannelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 23 mars 2018 10 h 33 CET
*/

public final class ChatChannelHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.ChatChannel value = null;

  public ChatChannelHolder ()
  {
  }

  public ChatChannelHolder (chat.ChatChannel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ChatChannelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ChatChannelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ChatChannelHelper.type ();
  }

}
