package chat;


/**
* chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 23 mars 2018 10 h 33 CET
*/

public interface ChatClientOperations 
{
  String getName ();
  void updateClientList (chat.ChatClient[] clients);
  void printMessage (chat.Message message);
  chat.Color getColor ();
  void shutdown ();
  org.omg.CORBA.Any getImage ();
} // interface ChatClientOperations
