package chat;


/**
* chat/ColorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 16 mars 2018 15 h 49 CET
*/

public interface ColorOperations 
{
  int getR ();
  int getG ();
  int getB ();
} // interface ColorOperations
