package chat;


/**
* chat/ColorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 16 mars 2018 15 h 49 CET
*/

public abstract class ColorPOA extends org.omg.PortableServer.Servant
 implements chat.ColorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getR", new java.lang.Integer (0));
    _methods.put ("getG", new java.lang.Integer (1));
    _methods.put ("getB", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/Color/getR
       {
         int $result = (int)0;
         $result = this.getR ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // chat/Color/getG
       {
         int $result = (int)0;
         $result = this.getG ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // chat/Color/getB
       {
         int $result = (int)0;
         $result = this.getB ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Color:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Color _this() 
  {
    return ColorHelper.narrow(
    super._this_object());
  }

  public Color _this(org.omg.CORBA.ORB orb) 
  {
    return ColorHelper.narrow(
    super._this_object(orb));
  }


} // class ColorPOA
