package chat;

/**
* chat/ColorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 16 mars 2018 15 h 49 CET
*/

public final class ColorHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Color value = null;

  public ColorHolder ()
  {
  }

  public ColorHolder (chat.Color initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ColorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ColorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ColorHelper.type ();
  }

}
