package corba_chat;

/**
* corba_chat/ChatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba_chat.idl
* vendredi 17 février 2017 12 h 36 CET
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public corba_chat.ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (corba_chat.ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba_chat.ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba_chat.ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba_chat.ChatClientHelper.type ();
  }

}
