package corba_chat;


/**
* corba_chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba_chat.idl
* vendredi 17 février 2017 12 h 36 CET
*/

public interface ChatClientOperations 
{
  String getUserName ();
  void addMSG (String msg);
  void updateConnectedUsers (String[] names);
} // interface ChatClientOperations
