package corba_chat;


/**
* corba_chat/ChatClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba_chat.idl
* vendredi 17 février 2017 12 h 36 CET
*/

public abstract class ChatClientPOA extends org.omg.PortableServer.Servant
 implements corba_chat.ChatClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getUserName", new java.lang.Integer (0));
    _methods.put ("addMSG", new java.lang.Integer (1));
    _methods.put ("updateConnectedUsers", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba_chat/ChatClient/getUserName
       {
         String $result = null;
         $result = this.getUserName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba_chat/ChatClient/addMSG
       {
         String msg = in.read_string ();
         this.addMSG (msg);
         out = $rh.createReply();
         break;
       }

       case 2:  // corba_chat/ChatClient/updateConnectedUsers
       {
         String names[] = corba_chat.NamesHelper.read (in);
         this.updateConnectedUsers (names);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba_chat/ChatClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatClient _this() 
  {
    return ChatClientHelper.narrow(
    super._this_object());
  }

  public ChatClient _this(org.omg.CORBA.ORB orb) 
  {
    return ChatClientHelper.narrow(
    super._this_object(orb));
  }


} // class ChatClientPOA
