package corba_chat;


/**
* corba_chat/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba_chat.idl
* vendredi 17 février 2017 12 h 36 CET
*/

public interface ChatServerOperations 
{
  void register (corba_chat.ChatClient c);
  void unRegister (corba_chat.ChatClient c);
  void sendToAll (String msg, corba_chat.ChatClient from);
} // interface ChatServerOperations
