package accumulator;


/**
* accumulator/AccumulatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 9 mars 2018 13 h 52 CET
*/

public interface AccumulatorOperations 
{
  void add (int number);
} // interface AccumulatorOperations
