package universite;


/**
* universite/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* jeudi 17 mars 2016 11 h 05 CET
*/

public interface Etudiant extends EtudiantOperations, universite.Personne, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
