package universite;


/**
* universite/PersonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* jeudi 17 mars 2016 11 h 05 CET
*/

public interface PersonneOperations 
{
  String nom ();
  void nom (String newNom);
} // interface PersonneOperations
