package universite;


/**
* universite/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 11 mars 2016 15 h 49 CET
*/

public interface Etudiant extends EtudiantOperations, universite.Personne, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
