package universite;


/**
* universite/PersonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 11 mars 2016 15 h 49 CET
*/

public interface PersonneOperations 
{
  String nom ();
  void nom (String newNom);
} // interface PersonneOperations
