package callbacks;


/**
* callbacks/CallbackClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 16 mars 2018 11 h 22 CET
*/

public interface CallbackClient extends CallbackClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackClient
