package callbacks;


/**
* callbacks/CallbackClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 16 mars 2018 11 h 22 CET
*/

public interface CallbackClientOperations 
{
  String getName ();
  void showYourName ();
} // interface CallbackClientOperations
