package callbacks;


/**
* callbacks/CallbackServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 16 mars 2018 11 h 22 CET
*/

public interface CallbackServerOperations 
{
  void sayHello ();
  void register (callbacks.CallbackClient client);
} // interface CallbackServerOperations
