package callbacks;


/**
* callbacks/CallbackServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 16 mars 2018 11 h 22 CET
*/

public interface CallbackServer extends CallbackServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackServer
