package universite;


/**
* universite/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.ild
* vendredi 9 mars 2018 15 h 23 CET
*/

public interface Etudiant extends EtudiantOperations, universite.Personne, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
