package universite;


/**
* universite/FacOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.ild
* vendredi 9 mars 2018 15 h 23 CET
*/

public interface FacOperations 
{
  universite.Etudiant ajouterEtudiant (String nom);
  universite.Etudiant recupererEtudiant (int numCarte);
  void retirerEtudiant (int numCarte);
  universite.Etudiant[] listerEtudiants ();
} // interface FacOperations
