package universite;


/**
* universite/PersonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.ild
* vendredi 9 mars 2018 15 h 23 CET
*/

public interface PersonneOperations 
{
  String nom ();
  void nom (String newNom);
} // interface PersonneOperations
