package accumulator;


/**
* accumulator/Accumulator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 17 février 2017 13 h 46 CET
*/

public interface Accumulator extends AccumulatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Accumulator
