package accumulator;


/**
* accumulator/AccumulatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 17 février 2017 13 h 46 CET
*/

public interface AccumulatorOperations 
{
  void add (int number);
} // interface AccumulatorOperations
