package universite.EtudiantPackage;

/**
* universite/EtudiantPackage/ResultatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.ild
* vendredi 9 mars 2018 15 h 23 CET
*/

public final class ResultatHolder implements org.omg.CORBA.portable.Streamable
{
  public universite.EtudiantPackage.Resultat value = null;

  public ResultatHolder ()
  {
  }

  public ResultatHolder (universite.EtudiantPackage.Resultat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = universite.EtudiantPackage.ResultatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    universite.EtudiantPackage.ResultatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return universite.EtudiantPackage.ResultatHelper.type ();
  }

}
