package helloApp;


/**
* helloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from helloApp.idl
* mardi 31 mai 2016 12 h 56 CEST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
