package helloApp;


/**
* helloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from helloApp.idl
* mardi 31 mai 2016 12 h 56 CEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
