package chat.ChatServerPackage;


/**
* chat/ChatServerPackage/channelsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 23 mars 2018 10 h 33 CET
*/

public final class channelsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public channelsHolder ()
  {
  }

  public channelsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ChatServerPackage.channelsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ChatServerPackage.channelsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ChatServerPackage.channelsHelper.type ();
  }

}
